### ISSUE TITLE
You should not use <Switch> outside a <Router>

### ISSUE THREAD

**Issue by MasterShu** [modern-js-dev/modern-js-examples#13]
Following tutorials/c8， I've got this error.
```bash
SSR Error - App Prefetch error = Error: Invariant failed: You should not use <Switch> outside a <Router>
    at invariant (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:22743:11)
    at Object.children (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:20919:19)
    at ReactDOMServerRenderer.render (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3972:55)
    at ReactDOMServerRenderer.read (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2635:36
    at AsyncLocalStorage.run (async_hooks.js:303:14)
    at run (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2494:40)
    at prefetch (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2632:56)
    at /Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2578:81
SSR Error - App Prefetch error = Error: Invariant failed: You should not use <Switch> outside a <Router>
    at invariant (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:22743:11)
    at Object.children (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:20919:19)
    at ReactDOMServerRenderer.render (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3972:55)
    at ReactDOMServerRenderer.read (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2635:36
    at AsyncLocalStorage.run (async_hooks.js:303:14)
    at run (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2494:40)
    at prefetch (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2632:56)
    at /Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2578:81
SSR Error - App Prefetch error = Error: Invariant failed: You should not use <Switch> outside a <Router>
    at invariant (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:22743:11)
    at Object.children (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:20919:19)
    at ReactDOMServerRenderer.render (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3972:55)
    at ReactDOMServerRenderer.read (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2635:36
    at AsyncLocalStorage.run (async_hooks.js:303:14)
    at run (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2494:40)
    at prefetch (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2632:56)
    at /Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2578:81
SSR Error - App Prefetch error = Error: Invariant failed: You should not use <Switch> outside a <Router>
    at invariant (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:22743:11)
    at Object.children (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:20919:19)
    at ReactDOMServerRenderer.render (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3972:55)
    at ReactDOMServerRenderer.read (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (/Volumes/Common/code/opensource/hello-modern/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2635:36
    at AsyncLocalStorage.run (async_hooks.js:303:14)
    at run (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2494:40)
    at prefetch (/Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2632:56)
    at /Volumes/Common/code/opensource/hello-modern/dist/bundles/contacts.js:2578:81

```

Example code `src/contacts/App.tsx`
```tsx
function App() {
  return (
    <div className="container lg mx-auto">
      <Switch>
        <Route path="/" exact={true}>
          <Helmet>
            <title>All</title>
          </Helmet>
          <List
            dataSource={mockData}
            renderItem={info => <Item key={info.name} info={info} />}
          />
        </Route>
        <Route path="/archives" exact={true}>
          <Helmet>
            <title>Archives</title>
          </Helmet>
          <List
            dataSource={mockArchivedData}
            renderItem={info => <Item key={info.name} info={info} />}
          />
        </Route>
      </Switch>
    </div>
  );
}
```

**Comment by anc95** [comment]
You can check have you enabled `modernConfig.runtime.router` in `package.json`, When you create a mwa project by `npx @modern-js/create` it's on by default.
https://github.com/modern-js-dev/modern-js-examples/blob/main/tutorials/c02/hello-modern/package.json#L50-L55
